spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/documents/workspace/songspy/songspy;NON_KEYWORDS=USER
    username: sa
    password:
  jpa:
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false

---
spring.profiles.active:
  - dev

spring:
  datasource:
    main:
      poolName: MainPool
      jdbc-url: jdbc:mysql://localhost:3306/songspy
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
